-- MySQL Script generated by MySQL Workbench
-- Chủ nhật, 16 Tháng 2 Năm 2020 00:19:45 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema work_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema work_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `work_management` DEFAULT CHARACTER SET utf8 ;
USE `work_management` ;

-- -----------------------------------------------------
-- Table `work_management`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_management`.`profile` (
  `profile_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `full_name` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `avatar` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `addres` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phone_number` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`profile_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `work_management`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_management`.`work` (
  `work_id` INT(11) NOT NULL AUTO_INCREMENT,
  `work_name` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `creator_id` INT(11) NOT NULL,
  `time_start` DATE NULL DEFAULT NULL,
  `time_end` DATETIME NULL DEFAULT NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `work_management`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_management`.`comment` (
  `comment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `profile_id` INT(11) NOT NULL,
  `work_id` INT(11) NOT NULL,
  `content` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `work_management`.`friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_management`.`friend` (
  `friend_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sender_id` INT(11) NOT NULL,
  `receiver_id` INT(11) NOT NULL,
  `is_accept` INT(11) NULL DEFAULT NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`friend_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;




-- -----------------------------------------------------
-- Table `work_management`.`work_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_management`.`work_details` (
  `work_id` INT(11) NOT NULL,
  `profile_id` INT(11) NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `work_plan` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `work_actual` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `work_next` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `work_issua` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `time_report` DATE NULL DEFAULT NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_id`, `profile_id`),
  INDEX `fk_work_details_2_idx` (`profile_id` ASC),
  CONSTRAINT `fk_work_details_1`
    FOREIGN KEY (`work_id`)
    REFERENCES `work_management`.`work` (`work_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_details_2`
    FOREIGN KEY (`profile_id`)
    REFERENCES `work_management`.`profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
